// <auto-generated />
using System;
using AnimeFlix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeFlixBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215143855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeFlix.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("AnimeApiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            AnimeApiId = 32,
                            CreatedAt = new DateTime(2025, 12, 15, 16, 38, 55, 149, DateTimeKind.Local).AddTicks(4738),
                            ReviewText = "Amazing anime! Great action scenes.",
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 2,
                            AnimeApiId = 30,
                            CreatedAt = new DateTime(2025, 12, 15, 16, 38, 55, 149, DateTimeKind.Local).AddTicks(4749),
                            ReviewText = "Very emotional story. Loved it!",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AnimeFlix.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 12, 15, 16, 38, 55, 149, DateTimeKind.Local).AddTicks(3500),
                            Email = "esraa@example.com",
                            PasswordHash = "e3afed0047b08059d0fada10f400c1e5",
                            Username = "Esraa"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 12, 15, 16, 38, 55, 149, DateTimeKind.Local).AddTicks(3515),
                            Email = "ali@example.com",
                            PasswordHash = "e3afed0047b08059d0fada10f400c1e5",
                            Username = "Ali"
                        });
                });

            modelBuilder.Entity("AnimeFlix.Models.UserPreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferenceId"));

                    b.Property<string>("FavoriteGenres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredMood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");

                    b.HasData(
                        new
                        {
                            PreferenceId = 1,
                            FavoriteGenres = "Action,Adventure",
                            PreferredMood = "Excited",
                            UserId = 1
                        },
                        new
                        {
                            PreferenceId = 2,
                            FavoriteGenres = "Romance,Drama",
                            PreferredMood = "Relaxed",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AnimeFlix.Models.WatchHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("AnimeApiId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WatchStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchHistories");

                    b.HasData(
                        new
                        {
                            HistoryId = 1,
                            AnimeApiId = 32,
                            UserId = 1,
                            WatchStatus = "Watching",
                            WatchedAt = new DateTime(2025, 12, 14, 16, 38, 55, 149, DateTimeKind.Local).AddTicks(4489)
                        },
                        new
                        {
                            HistoryId = 2,
                            AnimeApiId = 30,
                            UserId = 2,
                            WatchStatus = "Completed",
                            WatchedAt = new DateTime(2025, 12, 10, 16, 38, 55, 149, DateTimeKind.Local).AddTicks(4508)
                        });
                });

            modelBuilder.Entity("AnimeFlix.Models.Review", b =>
                {
                    b.HasOne("AnimeFlix.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeFlix.Models.UserPreference", b =>
                {
                    b.HasOne("AnimeFlix.Models.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("AnimeFlix.Models.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeFlix.Models.WatchHistory", b =>
                {
                    b.HasOne("AnimeFlix.Models.User", "User")
                        .WithMany("WatchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeFlix.Models.User", b =>
                {
                    b.Navigation("Preference")
                        .IsRequired();

                    b.Navigation("Reviews");

                    b.Navigation("WatchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
